// Weather condition keys
const CLEAR_SKY_KEY = 0;
const MAIN_CLEARLY_PARTLY_SKY_KEY = 1;
const MAIN_CLEARLY_CLOUDY_SKY_KEY = 2;
const MAIN_CLEARLY_OVERCAST_SKY_KEY = 3;
const FOG_SKY_KEY = 45;
const RIME_FOG_SKY_KEY = 48;
const DRIZZLE_LIGHT_SKY_KEY = 51;
const DRIZZLE_MODERATE_SKY_KEY = 53;
const DRIZZLE_DENSE_SKY_KEY = 55;
const FREEZING_DRIZZLE_LIGHT_KEY = 56;
const FREEZING_DRIZZLE_DENSE_KEY = 57;
const RAIN_SLIGHT_KEY = 61;
const RAIN_MODERATE_KEY = 63;
const RAIN_DENSE_KEY = 65;
const FREEZING_RAIN_LIGHT = 66;
const FREEZING_RAIN_DENSE = 67;
// Image paths corresponding to different weather conditions
const CLEAR_SKY_IMAGE = "/assets/sun.png";
const MAIN_CLEARLY_SKY_IMAGE = "/assets/sun_clearly.png";
const FOG_SKY_IMAGE = "/assets/fog.png";
const DRIZZLE_SKY_IMAGE = "/assets/drizzle.png";
const FREEZING_DRIZZLE_SKY_IMAGE = "/assets/freezing_drizzle.png";
const RAIN_SKY_IMAGE = "/assets/rain.png";
const FREEZING_RAIN_SKY_IMAGE = "/assets/freezing_rain.png";
// Map weather condition keys to their corresponding images
export const TIME_VARIANTS = {
  [CLEAR_SKY_KEY]: CLEAR_SKY_IMAGE,
  [MAIN_CLEARLY_PARTLY_SKY_KEY]: MAIN_CLEARLY_SKY_IMAGE,
  [MAIN_CLEARLY_CLOUDY_SKY_KEY]: MAIN_CLEARLY_SKY_IMAGE,
  [MAIN_CLEARLY_OVERCAST_SKY_KEY]: MAIN_CLEARLY_SKY_IMAGE,
  [FOG_SKY_KEY]: FOG_SKY_IMAGE,
  [RIME_FOG_SKY_KEY]: FOG_SKY_IMAGE,
  [DRIZZLE_LIGHT_SKY_KEY]: DRIZZLE_SKY_IMAGE,
  [DRIZZLE_MODERATE_SKY_KEY]: DRIZZLE_SKY_IMAGE,
  [DRIZZLE_DENSE_SKY_KEY]: DRIZZLE_SKY_IMAGE,
  [FREEZING_DRIZZLE_LIGHT_KEY]: FREEZING_DRIZZLE_SKY_IMAGE,
  [FREEZING_DRIZZLE_DENSE_KEY]: FREEZING_DRIZZLE_SKY_IMAGE,
  [RAIN_SLIGHT_KEY]: RAIN_SKY_IMAGE,
  [RAIN_MODERATE_KEY]: RAIN_SKY_IMAGE,
  [RAIN_DENSE_KEY]: RAIN_SKY_IMAGE,
  [FREEZING_RAIN_LIGHT]: FREEZING_RAIN_SKY_IMAGE,
  [FREEZING_RAIN_DENSE]: FREEZING_RAIN_SKY_IMAGE,
};
